### ISSUE TITLE
Unable to parse response with Piwigo 2.8

### ISSUE THREAD

**Issue by rorrison** [Piwigo/Piwigo-Java#3]
I've just updated my site to Piwigo 2.8, and am getting the following error:

```
[INFO] User randy will sync gallery https://orrison.com/gallery with directory D:\Piwigo
[INFO] will create album for D:\Piwigo\Slides1960s
[INFO] Connecting... 
[INFO] Connect successful
[ERROR] Unable to parse response
[ERROR] Cannot create album for D:\Piwigo\Slides1960s
[INFO] will upload image for D:\Piwigo\Slides1960s\01-59-001.JPG in album with id null
[ERROR] Unable to parse response
... etc ...
```

I hadn't tried piwigo sync on my live site before this, so I don't know if it worked with 2.7.

**Comment by rorrison** [comment]
I've attached a debug log file from running

```
"\Program Files\Java\jre1.8.0_77\bin\java.exe" -jar remotesync-ui.jar -debug > javalog.txt
```

It is a different exception from #2 
[javalog.txt](https://github.com/Piwigo/Piwigo-Java/files/214938/javalog.txt)

**Comment by mhelleboid** [comment]
Can you make a new test on a piwigo 2.8 version?

**Comment by rorrison** [comment]
Working fine on my test site running 2.8.2 - thanks!
