### ISSUE TITLE
Use a specific user agent

### ISSUE THREAD

**Issue by plegall** [Piwigo/Piwigo-Java#7]
When performing HTTP requests, instead of `Apache-HttpClient/4.3.4 (java 1.5)` it would be much more useful to have "PiwigoRemoteSync 0.0.13".

**Comment by plegall** [comment]
up, @mhelleboid can you add a more specific user agent ? :-)

**Comment by Valou447** [comment]
Hello @plegall, this feature will be included in the 0.0.14 version.

Thank you.
